### PR TITLE
Render and replace current placeholder graphics, closes #2

### LINKED ISSUE #2: Render and replace current placeholder graphics.
Create and render two Minecraft related images for the websites and plugins section.
- Required size 240px by 169px  
  Height can be any value less than the width, however, both images should preferably be the same size.
- Similar style to the main oc.tc websites "Variety", "Competition" & "Reliability" images.

Suggestions:  
- For the "Plugins" section a fully armoured player holding a command block / standing beside one.
- For the "Website" section, a player reading a book / sitting on a bookshelf, several players standing in a group / talking.

### PR DESCRIPTION
**Pull request by TiTo-418**
@McSpider Thanks to <a href="https://oc.tc/Sr_Elmo">Sr_Elmo</a>!!! 
He made these amazing images!
Topic: https://oc.tc/forums/topics/556146125f35b95b3b0080ce

### CODE REVIEW

**Comment by TiTo-418** [comment]
If you merge this and https://github.com/OvercastNetwork/translate.oc.tc/pull/4, https://github.com/OvercastNetwork/Issues/issues/1699 can be closed

**Comment by matic0basle** [comment]
These look cool but you should have used the default resource pack and the skins could also be different but its nice.

**Comment by nanuscience** [comment]
I recommend you to use Steve or Alex skin (because is original) and use default texture pack.
Also you and use a new 3D bookshelf from rymdnisse.net is pretty good rig !

-SORRY FOR BAD GRAMMAR
image
image

**Comment by Brottweiler** [comment]
I agree, you should really use default texturepack, and maybe even default skins (Steve and Alex).

**Comment by TiTo-418** [comment]
Ok! Im going to talk with Sr_Elmo. Thanks!

**Pull request closed without merging**
